### ISSUE TITLE
Underline is removed when loading Stres a choroby (5457d0a7-c6a2-418d-adb2-2dfecf04d6d7)

### ISSUE THREAD

**Issue by aiwenar** [openstax-poland/cnx-designer#131]

**Comment by aiwenar** [comment]
This is also the case for _Dążenie do szczęścia_ (6a55f4cb-9992-41ab-a7b6-779ba3119a51).

**Comment by MartaSztuka** [comment]
##### PASSED

GIVEN Login to [base-url]
AND Draft in which you have editing permissions is open
AND Some text is selected
AND Click Underline in toolbox
WHEN Page is refreshed
THEN Selected text is still undelined
