### ISSUE TITLE
Editor allows duplicate IDs to occur

### ISSUE THREAD

**Issue by aiwenar** [openstax-poland/cnx-designer#146]

**Comment by MartaSztuka** [comment]
@aiwenar Problem still occurs, 
IDs duplicates for media alt, terms, notes and links
Here's footage, draft link and errors list:
https://watch.screencastify.com/v/FkRNtjhoF3v0Owb4W5p7
https://adaptarr-testing.naukosfera.org/drafts/f4c21722-1f51-41fb-8d97-a995811f4f6b/edit
index.cnxml:38:90: error: ID "fs-idm83385920" has already been defined
index.cnxml:7:90: error: first occurrence of ID "fs-idm83385920" index.cnxml:42:34: error: ID "fs-idp136951760" has already been defined index.cnxml:12:32: error: first occurrence of ID "fs-idp136951760" index.cnxml:43:70: error: ID "fs-idp57248112" has already been defined index.cnxml:13:68: error: first occurrence of ID "fs-idp57248112" index.cnxml:44:36: error: ID "fs-idp159987488" has already been defined index.cnxml:14:34: error: first occurrence of ID "fs-idp159987488" index.cnxml:46:33: error: ID "fs-idp34661824" has already been defined index.cnxml:16:31: error: first occurrence of ID "fs-idp34661824" index.cnxml:56:36: error: ID "fs-idp129892576" has already been defined index.cnxml:26:34: error: first occurrence of ID "fs-idp129892576"
