### ISSUE TITLE
Numbering of solutions doesn't work in drafts

### ISSUE THREAD

**Issue by uskka** [openstax-poland/cnx-designer#9]
Every solution has number 1. 
https://adaptarr.naukosfera.com/drafts/3f3175f8-cfbc-4a8e-af4e-5bf0a7170f66

**Comment by aiwenar** [comment]
Do they stay at 1 after you focus (place cursor in) the editor?

**Comment by PiotrKozlowski** [comment]
@MartaSztuka Could you check if this issue still occurs?

**Comment by MartaSztuka** [comment]
Issue does not occur anymore.
